<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sable.Core\Sable.Core.csproj" />
    <ProjectReference Include="..\..\src\Sable.Engine\Sable.Engine.csproj" />
    <ProjectReference Include="..\..\src\Sable.Tools\Sable.Tools.csproj" />
    <ProjectReference Include="..\..\src\Sable.Format\Sable.Format.csproj" />
    <ProjectReference Include="..\..\src\Sable.Imaging\Sable.Imaging.csproj" />
    <ProjectReference Include="..\..\src\Sable.Gpu\Sable.Gpu.csproj" />
    <ProjectReference Include="..\..\src\Sable.Ai\Sable.Ai.csproj" />
  </ItemGroup>

</Project>